### ISSUE TITLE
Implement an indicator to show if connection to MM is lost

### ISSUE THREAD

**Issue by jansako** [lukechilds/hyperdex-bugtracker#8]
After running HyperDEX for a while (~1 hour), executing a few trades & deposits, it seems MM/komodod has stopped responding. the UI itself (switching tabs & clicking on price to fill the appropriate boxes) still works, but there is no response to:

- receiving coins (the balance does not update)
- starting a trade (no errors, just nothing happens)
- when switching to a different coin, the orderbook no longer updates

Is there any logging that I can turn on? let me know what else can I provide.

Win 10.

**Comment by lukechilds** [comment]
Thanks for reporting, you can open the network tab in dev tools and view the requests we're making to mm. Clicking on them will show you the data sent and received.

<img width="1109" alt="screen shot 2018-05-02 at 2 04 04 pm" src="https://user-images.githubusercontent.com/2123375/39509785-b0f9ce74-4e11-11e8-8640-38673e20da4c.png">

If mm is responding to requests with incorrect data then it needs to be fixed on mms end. Otherwise, if possible, we should report when mm becomes inactive.

**Comment by jansako** [comment]
I will leave HyperDEX running & see if I can reproduce.

**Comment by sindresorhus** [comment]
Moved to https://github.com/lukechilds/hyperdex/issues/260
